### ISSUE TITLE
Add Comando GIT Bash para configurar PROXY

### ISSUE THREAD

**Issue by jeanfbd** [urielcaire/gitbasico#1]
git config --global http.sslVerify false

git config --global http.proxy http://usuario:senha@host:port

usuario: deve contar o login para o proxy;
senha: a senha do proxy;
host: o ip do servidor proxy;
port: a porta do proxy;
EX: git config --global http.proxy http://jeanbrock:SENHA@forceproxy.tj.sp.intranet:8080

**Comment by urielcalvi** [comment]
@jeanfbd a configuração de proxy foi adicionado ao conteúdo!!!! Obrigado por sua observação!! :smiley:
